feat: Add a web page to list elements.
gkmahendran09/training pull request #22
Opened 2024-02-01 15:53 UTC by adithyanmadhi

# JavaScript web app / web site exercise beginner practice.
![Screenshot 2024-02-01 195348](https://github.com/gkmahendran09/training/assets/154506917/6f97780d-39f1-4fde-8ba5-6a257aa4446c)
![Screenshot 2024-02-01 195449](https://github.com/gkmahendran09/training/assets/154506917/37c05d8a-686b-4f77-9dc0-996fe6686753)

Jira link:
https://mahendrankannan.atlassian.net/browse/ON-29

2024-02-02 05:18 UTC, gkmahendran09 requested changes

2024-02-02 05:18 UTC, gkmahendran09 commented on web-application/elements-listing-page/index.html
> +      <input type="text" id="add-Player" placeholder="Add player name...">
`id` can be small case

2024-02-04 18:34 UTC, adithyanmadhi commented on web-application/elements-listing-page/index.html
> +      <input type="text" id="add-Player" placeholder="Add player name...">
Updated

2024-02-06 05:06 UTC, gkmahendran09 approved these changes

2024-02-06 05:08 UTC, gkmahendran09 approved these changes

2024-02-07 04:39 UTC, merged