feat: Add a mini project.
gkmahendran09/training pull request #39
Opened 2024-02-19 05:02 UTC by adithyanmadhi

Mini Project: Build a mini social media web app.

![Screenshot 2024-02-19 102826](https://github.com/gkmahendran09/training/assets/154506917/bb0e2720-4f99-4b9d-8204-db7da79f7c6f)

![Screenshot 2024-02-19 102810](https://github.com/gkmahendran09/training/assets/154506917/938af693-025c-4722-934b-d4ef54359c27)
Jira Link:
https://mahendrankannan.atlassian.net/browse/ON-38

2024-02-27 06:01 UTC, gkmahendran09 requested changes

2024-02-27 06:01 UTC, gkmahendran09 commented on web-application/mini-project/script.js
> +                location: null,
Some improvements to displaying the location
- Display the lat and long details obtained from HTML5 and display it under the post
- Try to integrate Google Maps SDK and show a mini-map of the post location by passing the lat, long details and display it under the post.

2024-02-27 20:44 UTC, adithyanmadhi commented on web-application/mini-project/script.js
> +            this.posts = this.posts.filter(post => post.id !== id);
Used splice.

2024-02-28 05:20 UTC, gkmahendran09 approved these changes

2024-02-28 16:00 UTC, merged